"""List of all chaotic system names available in the dysts.flows module.

Generated via `causaldynamics.systems.get_all_chaotic_system_names()` and
`causaldynamics.systems.get_all_chaotic_system_names_and_dimensions()`.
"""

system_name_list = [
    "Aizawa",
    "AnishchenkoAstakhov",
    "Arneodo",
    "ArnoldBeltramiChildress",
    "ArnoldWeb",
    "AtmosphericRegime",
    "BeerRNN",
    "BelousovZhabotinsky",
    "BickleyJet",
    "Blasius",
    "BlinkingRotlet",
    "BlinkingVortex",
    "Bouali",
    "Bouali2",
    "BurkeShaw",
    "CaTwoPlus",
    "CaTwoPlusQuasiperiodic",
    "CellCycle",
    "CellularNeuralNetwork",
    "Chen",
    "ChenLee",
    "Chua",
    "CircadianRhythm",
    "CoevolvingPredatorPrey",
    "Colpitts",
    "Coullet",
    "Dadras",
    "DequanLi",
    "DoubleGyre",
    "DoublePendulum",
    "Duffing",
    "ExcitableCell",
    "Finance",
    "FluidTrampoline",
    "ForcedBrusselator",
    "ForcedFitzHughNagumo",
    "ForcedVanDerPol",
    "GenesioTesi",
    "GlycolyticOscillation",
    "GuckenheimerHolmes",
    "Hadley",
    "Halvorsen",
    "HastingsPowell",
    "HenonHeiles",
    "HindmarshRose",
    "Hopfield",
    "HyperBao",
    "HyperCai",
    "HyperJha",
    "HyperLorenz",
    "HyperLu",
    "HyperPang",
    "HyperQi",
    "HyperRossler",
    "HyperWang",
    "HyperXu",
    "HyperYan",
    "HyperYangChen",
    "IkedaDelay",
    "InteriorSquirmer",
    "IsothermalChemical",
    "ItikBanksTumor",
    "JerkCircuit",
    "KawczynskiStrizhak",
    "Laser",
    "LidDrivenCavityFlow",
    "LiuChen",
    "Lorenz",
    "Lorenz84",
    "Lorenz96",
    "LorenzBounded",
    "LorenzCoupled",
    "LorenzStenflo",
    "LuChen",
    "LuChenCheng",
    "MacArthur",
    "MackeyGlass",
    "MooreSpiegel",
    "MultiChua",
    "NewtonLiepnik",
    "NoseHoover",
    "NuclearQuadrupole",
    "OscillatingFlow",
    "PanXuZhou",
    "PehlivanWei",
    "PiecewiseCircuit",
    "Qi",
    "QiChen",
    "RabinovichFabrikant",
    "RayleighBenard",
    "RikitakeDynamo",
    "Rossler",
    "Rucklidge",
    "Sakarya",
    "SaltonSea",
    "SanUmSrisuchinwong",
    "ScrollDelay",
    "ShimizuMorioka",
    "SprottA",
    "SprottB",
    "SprottC",
    "SprottD",
    "SprottDelay",
    "SprottE",
    "SprottF",
    "SprottG",
    "SprottH",
    "SprottI",
    "SprottJ",
    "SprottJerk",
    "SprottK",
    "SprottL",
    "SprottM",
    "SprottMore",
    "SprottN",
    "SprottO",
    "SprottP",
    "SprottQ",
    "SprottR",
    "SprottS",
    "SprottTorus",
    "StickSlipOscillator",
    "SwingingAtwood",
    "Thomas",
    "ThomasLabyrinth",
    "Torus",
    "Tsucs2",
    "TurchinHanski",
    "VallisElNino",
    "VossDelay",
    "WangSun",
    "WindmiReduced",
    "YuWang",
    "YuWang2",
    "ZhouChen",
]

system_name_to_dimension = {
    "Aizawa": 3,
    "AnishchenkoAstakhov": 3,
    "Arneodo": 3,
    "ArnoldBeltramiChildress": 3,
    "ArnoldWeb": 5,
    "AtmosphericRegime": 3,
    "BeerRNN": 3,
    "BelousovZhabotinsky": 3,
    "BickleyJet": 3,
    "Blasius": 3,
    "BlinkingRotlet": 3,
    "BlinkingVortex": 3,
    "Bouali": 3,
    "Bouali2": 3,
    "BurkeShaw": 3,
    "CaTwoPlus": 3,
    "CaTwoPlusQuasiperiodic": 3,
    "CellCycle": 6,
    "CellularNeuralNetwork": 3,
    "Chen": 3,
    "ChenLee": 3,
    "Chua": 3,
    "CircadianRhythm": 5,
    "CoevolvingPredatorPrey": 3,
    "Colpitts": 3,
    "Coullet": 3,
    "Dadras": 3,
    "DequanLi": 3,
    "DoubleGyre": 3,
    "DoublePendulum": 4,
    "Duffing": 3,
    "ExcitableCell": 3,
    "Finance": 3,
    "FluidTrampoline": 3,
    "ForcedBrusselator": 3,
    "ForcedFitzHughNagumo": 3,
    "ForcedVanDerPol": 3,
    "GenesioTesi": 3,
    "GlycolyticOscillation": 3,
    "GuckenheimerHolmes": 3,
    "Hadley": 3,
    "Halvorsen": 3,
    "HastingsPowell": 3,
    "HenonHeiles": 4,
    "HindmarshRose": 3,
    "Hopfield": 6,
    "HyperBao": 4,
    "HyperCai": 4,
    "HyperJha": 4,
    "HyperLorenz": 4,
    "HyperLu": 4,
    "HyperPang": 4,
    "HyperQi": 4,
    "HyperRossler": 4,
    "HyperWang": 4,
    "HyperXu": 4,
    "HyperYan": 4,
    "HyperYangChen": 4,
    "IkedaDelay": 10,
    "InteriorSquirmer": 3,
    "IsothermalChemical": 3,
    "ItikBanksTumor": 3,
    "JerkCircuit": 3,
    "KawczynskiStrizhak": 3,
    "Laser": 3,
    "LidDrivenCavityFlow": 3,
    "LiuChen": 3,
    "Lorenz": 3,
    "Lorenz84": 3,
    "Lorenz96": 4,
    "LorenzBounded": 3,
    "LorenzCoupled": 6,
    "LorenzStenflo": 4,
    "LuChen": 3,
    "LuChenCheng": 3,
    "MacArthur": 10,
    "MackeyGlass": 10,
    "MooreSpiegel": 3,
    "MultiChua": 3,
    "NewtonLiepnik": 3,
    "NoseHoover": 3,
    "NuclearQuadrupole": 4,
    "OscillatingFlow": 3,
    "PanXuZhou": 3,
    "PehlivanWei": 3,
    "PiecewiseCircuit": 10,
    "Qi": 4,
    "QiChen": 3,
    "RabinovichFabrikant": 3,
    "RayleighBenard": 3,
    "RikitakeDynamo": 3,
    "Rossler": 3,
    "Rucklidge": 3,
    "Sakarya": 3,
    "SaltonSea": 3,
    "SanUmSrisuchinwong": 3,
    "ScrollDelay": 10,
    "ShimizuMorioka": 3,
    "SprottA": 3,
    "SprottB": 3,
    "SprottC": 3,
    "SprottD": 3,
    "SprottDelay": 10,
    "SprottE": 3,
    "SprottF": 3,
    "SprottG": 3,
    "SprottH": 3,
    "SprottI": 3,
    "SprottJ": 3,
    "SprottJerk": 3,
    "SprottK": 3,
    "SprottL": 3,
    "SprottM": 3,
    "SprottMore": 3,
    "SprottN": 3,
    "SprottO": 3,
    "SprottP": 3,
    "SprottQ": 3,
    "SprottR": 3,
    "SprottS": 3,
    "SprottTorus": 3,
    "StickSlipOscillator": 3,
    "SwingingAtwood": 4,
    "Thomas": 3,
    "ThomasLabyrinth": 3,
    "Torus": 3,
    "Tsucs2": 3,
    "TurchinHanski": 3,
    "VallisElNino": 3,
    "VossDelay": 10,
    "WangSun": 3,
    "WindmiReduced": 3,
    "YuWang": 3,
    "YuWang2": 3,
    "ZhouChen": 3,
}
